version: 2.1

defaults: &defaults
  docker:
    - image: google/cloud-sdk:alpine

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - restore_cache:
          key: npm-cache-{{ checksum "hash" }}

      - run:
          name: Installing dependencies ...
          command: npm install

      - save_cache:
          key: npm-cache-{{ checksum "hash" }}
          paths:
            - node_modules/

      - restore_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Dereferencing JSON Schemas ...
          command: ${HOME}/project/.circleci/dereference-json-schemas.sh

      - run:
          name: Faking data by JSON Schemas ...
          command: ${HOME}/project/.circleci/create-fake-json-data.sh

      - save_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/project/build"

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /root
          # Must be relative path from root
          paths:
            - project

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - run:
          name: Testing JSON Schemas units (typescript code) ...
          command: ${HOME}/project/.circleci/test-software.sh

      - run:
          name: Testing JSON Schemas syntax validity (specification) ...
          command: ${HOME}/project/.circleci/test-json-schemas.sh

      - run:
          name: Testing JSON Schemas against blueprint data (valid & invalid) ...
          command: ${HOME}/project/.circleci/test-json-data.sh

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - run:
          name: Authenticating with NPM registry ...
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ${HOME}/.npmrc 2>&1

      - run:
          name: Creating data-models-typescript (Interfaces, Factories, ...) ...
          command: ${HOME}/project/.circleci/create-data-models-typescript.sh

      - run:
          name: Cloning data-models-typescript repository ...
          command: ${HOME}/project/.circleci/clone-data-models-typescript-repository.sh

      - run:
          name: Publishing data-models-typescript ...
          no_output_timeout: 3m
          command: ${HOME}/project/.circleci/publish-data-models-typescript.sh

      - run:
          name: Publishing JSON Schemas ...
          command: ${HOME}/project/.circleci/publish.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: wunderbon-open-source-api
          filters:
            branches:
              only:
                - /^feature\/.+$/
                - develop
                - master
      - test:
          context: wunderbon-open-source-api
          requires:
            - build

  build-test-publish:
    jobs:
      - build:
          context: wunderbon-open-source-api
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - test:
          context: wunderbon-open-source-api
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - publish:
          context: wunderbon-open-source-api
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
