version: 2

defaults: &defaults
  docker:
    - image: circleci/node:chakracore-10.13.0

jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - save_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Dereference JSON SChemas
          command: ${HOME}/project/.circleci/dereference-json-schemas.sh

      - run:
          name: Validating JSON SChemas
          command: ${HOME}/project/.circleci/validate-json-schemas.sh

      - run:
          name: Validating JSON Schemas against Blueprint Model(s)
          command: ${HOME}/project/.circleci/validate-json-data.sh

      - run:
          name: Debug output
          command: ls -alR ${HOME}/project/.tmp

      - save_cache:
          key: cache-circleci-{{ checksum "CACHE_KEY" }}
          paths:
            - "~/project"

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: wunderbon-build-api-staging
