version: 2

defaults: &defaults
  docker:
    - image: google/cloud-sdk:alpine

jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - save_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - "~/project"

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - restore_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      - save_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

      - restore_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Dereferencing JSON Schemas ...
          command: ${HOME}/project/.circleci/dereference-json-schemas.sh

      - run:
          name: Faking data by JSON Schemas ...
          command: ${HOME}/project/.circleci/create-fake-json-data.sh

      - save_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/project/build"

  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - save_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - "~/project"

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - restore_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      - save_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - restore_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Testing JSON Schemas validity ...
          command: ${HOME}/project/.circleci/test-json-schemas.sh

      - run:
          name: Testing JSON Schema inplementations against blueprints ...
          command: ${HOME}/project/.circleci/test-json-data.sh

      - save_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - "build"

  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - save_cache:
          key: cache-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - "~/project"

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      - restore_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      - save_cache:
          key: cache-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - restore_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Creating TypeScript declarations ...
          command: ${HOME}/project/.circleci/create-typescript-declarations.sh

      - run:
          name: Cloning typescript-declaration repository ...
          command: ${HOME}/project/.circleci/clone-typescript-declarations-repository.sh

      #- run:
      #    name: Merging files for update! (git add / git commit / git pr)
      #    command: foo

      - run:
          name: DEBUG
          command: ls -alR /tmp/typescript-declarations

      - save_cache:
          key: cache-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - "build"

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: wunderbon-open-source-api
      - test:
          context: wunderbon-open-source-api
          requires:
            - build
      - deploy:
          context: wunderbon-open-source-api
          requires:
            - test
