version: 2

defaults: &defaults
  docker:
    - image: circleci/node:chakracore-10.13.0

jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      - save_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - save_cache:
          key: cache-circleci-{{ checksum "CACHE_KEY" }}
          paths:
            - "~/project"
