version: 2

defaults: &defaults
  docker:
    - image: google/cloud-sdk:alpine

jobs:
  build:
    <<: *defaults
    steps:
      #- restore_cache:
      #    key: cache-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      #- save_cache:
      #    key: cache-{{ .Branch }}-{{ .Revision }}
      #    paths:
      #      - "~/project"

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      #- restore_cache:
      #    key: cache-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      #- save_cache:
      #    key: cache-{{ checksum "package-lock.json" }}
      #    paths:
      #      - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

      - restore_cache:
          key: cache-tmp-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Dereferencing JSON Schemas ...
          command: ${HOME}/project/.circleci/dereference-json-schemas.sh

      - run:
          name: Faking data by JSON Schemas ...
          command: ${HOME}/project/.circleci/create-fake-json-data.sh

      - save_cache:
          key: cache-tmp-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/project/.tmp"

      #- save_cache:
      #    key: cache-circleci-{{ checksum "CACHE_KEY" }}
      #    paths:
      #      - "~/project"

  test:
    <<: *defaults
    steps:
      #- restore_cache:
       #   key: cache-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      #- save_cache:
       #   key: cache-{{ .Branch }}-{{ .Revision }}
      #    paths:
      #      - "~/project"

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      #- restore_cache:
      #    key: cache-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      #- save_cache:
      #    key: cache-{{ checksum "package-lock.json" }}
      #    paths:
      #      - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

      #- restore_cache:
      #    key: cache-circleci-{{ checksum "CACHE_KEY" }}

      - restore_cache:
          key: cache-tmp-{{ .Branch }}-{{ .Revision }}

      - run:
          name: DEBUG +++
          command: ls -alR ${HOME}/project/.tmp

      - run:
          name: Testing JSON Schemas validity ...
          command: ${HOME}/project/.circleci/test-json-schemas.sh

      - run:
          name: Testing JSON Schema inplementations against blueprints ...
          command: ${HOME}/project/.circleci/test-json-data.sh

      #- save_cache:
#          key: cache-circleci-{{ checksum "CACHE_KEY" }}
 #         paths:
  #          - "~/project"

  deploy:
    <<: *defaults
    steps:
      #- restore_cache:
      #    key: cache-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Tidy-Up git (git gc)
          command: git gc

      #- save_cache:
      #    key: cache-{{ .Branch }}-{{ .Revision }}
      #    paths:
      #      - "~/project"

      - run:
          name: Managing permissions ...
          command: chmod +x ${HOME}/project/.circleci/*.sh

      - run:
          name: Installing build tools ...
          command: ${HOME}/project/.circleci/install-buildtools.sh

      #- restore_cache:
      #    key: cache-{{ checksum "package-lock.json" }}

      - run:
          name: Installing packages ...
          command: npm install

      #- save_cache:
      #    key: cache-{{ checksum "package-lock.json" }}
      #    paths:
      #      - "node_modules"

      - run:
          name: Generating build cache key ...
          command: echo $(find ${HOME}/project/.circleci/ -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)  >> CACHE_KEY

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: wunderbon-open-source-api
      - test:
          context: wunderbon-open-source-api
          requires:
            - build
      - deploy:
          context: wunderbon-open-source-api
          requires:
            - test
